line_length:
  warning: 200
  error: 300

identifier_name:
  min_length:
    error: 2
  excluded:
    - r
    - g
    - b
    - a
    - x
    - y
    - z
    - id

function_body_length:
  warning: 100
  error: 150

disabled_rules:
  - force_cast

# See: https://github.com/realm/SwiftLint#configuration
